### PR TITLE
Add jquery function to main.js 

### PR DESCRIPTION
**Pull request by gportog**
[X] Change the menu in the index.php; :+1: 
[X] Create a function to click event in the menu. :+1:

### CODE REVIEW

**Comment by HugoLimaSantos** [comment]
I will check it, don´t worry 👍

**Comment by gportog** [comment]
Thanks! Hope you like it!  :smile:

**Comment by HugoLimaSantos** [comment]
Ok

**Comment by FlavioSilvaA** [comment]
Approved! :tada:

**Pull request merged**
